create table if not exists public.vehicle_specs (
  id uuid primary key default gen_random_uuid(),
  brand text not null,
  model text not null,
  default_fuel_type text not null default 'RON95',
  default_fuel_efficiency_km_per_liter numeric(6, 2),
  default_tank_capacity_liters numeric(6, 2),
  default_battery_capacity_kwh numeric(6, 2),
  data_confidence text not null default 'estimate',
  notes text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (brand, model)
);

insert into public.vehicle_specs (
  brand,
  model,
  default_fuel_type,
  default_fuel_efficiency_km_per_liter,
  default_tank_capacity_liters,
  default_battery_capacity_kwh,
  data_confidence,
  notes
) values
  ('Perodua', 'Axia', 'RON95', 27.40, 36.00, null, 'official/estimate', 'Variant/year dependent; Perodua publishes up to 27.4 km/L.'),
  ('Perodua', 'Bezza', 'RON95', 22.00, 36.00, null, 'estimate', 'Typical 1.3L/1.0L combined figure; verify by variant.'),
  ('Perodua', 'Myvi', 'RON95', 22.20, 36.00, null, 'official/estimate', '2022 facelift 1.3L published at 22.2 km/L and 36 L tank.'),
  ('Perodua', 'Ativa', 'RON95', 18.90, 36.00, null, 'official/estimate', 'Ativa 1.0L turbo published at 18.9 km/L and 36 L tank.'),
  ('Perodua', 'Alza', 'RON95', 22.00, 43.00, null, 'official/estimate', 'Alza D27A MDC figure 22 km/L; NEDC commonly 18.9 km/L.'),
  ('Perodua', 'Aruz', 'RON95', 15.60, 45.00, null, 'estimate', 'Variant/year dependent.'),

  ('Proton', 'Saga', 'RON95', 20.40, 40.00, null, 'official/estimate', 'Newer Saga MDC is around 4.9-5.1 L/100km; tank 40 L.'),
  ('Proton', 'Persona', 'RON95', 16.40, 40.00, null, 'estimate', 'Variant/year dependent.'),
  ('Proton', 'Iriz', 'RON95', 16.40, 40.00, null, 'estimate', 'Variant/year dependent.'),
  ('Proton', 'S70', 'RON95', 16.40, 50.00, null, 'estimate', 'Variant/year dependent.'),
  ('Proton', 'X50', 'RON95', 15.40, 45.00, null, 'official/estimate', 'X50 commonly listed around 6.4-6.5 L/100km and 45 L tank.'),
  ('Proton', 'X70', 'RON95', 13.50, 60.00, null, 'estimate', 'Variant/year dependent.'),
  ('Proton', 'X90', 'RON95', 15.40, 60.00, null, 'estimate', 'Mild-hybrid variants vary by trim and test cycle.'),

  ('Toyota', 'Vios', 'RON95', 19.20, 40.00, null, 'official/estimate', 'Toyota Malaysia lists Vios around 5.2 L/100km and 40 L tank.'),
  ('Toyota', 'Yaris', 'RON95', 17.90, 42.00, null, 'estimate', 'Variant/year dependent.'),
  ('Toyota', 'Corolla Altis', 'RON95', 15.60, 50.00, null, 'estimate', 'Variant/year dependent.'),
  ('Toyota', 'Corolla Cross', 'RON95', 16.70, 47.00, null, 'estimate', 'Hybrid/non-hybrid differs significantly.'),
  ('Toyota', 'Camry', 'RON95', 18.90, 50.00, null, 'estimate', 'Hybrid/non-hybrid differs significantly.'),
  ('Toyota', 'Innova', 'RON95', 12.50, 52.00, null, 'estimate', 'Variant/year dependent.'),
  ('Toyota', 'Fortuner', 'Diesel', 12.00, 80.00, null, 'estimate', 'Diesel/petrol variants differ.'),
  ('Toyota', 'Hilux', 'Diesel', 11.50, 80.00, null, 'official/estimate', 'Toyota Malaysia lists 80 L tank; efficiency varies by engine/drivetrain.'),
  ('Toyota', 'Hiace', 'Diesel', 10.00, 70.00, null, 'estimate', 'Variant/year dependent.'),

  ('Honda', 'City', 'RON95', 17.50, 40.00, null, 'estimate', 'Petrol/e:HEV hybrid differs significantly.'),
  ('Honda', 'City Hatchback', 'RON95', 17.50, 40.00, null, 'estimate', 'Petrol/e:HEV hybrid differs significantly.'),
  ('Honda', 'Civic', 'RON95', 15.60, 47.00, null, 'estimate', 'Petrol/e:HEV hybrid differs significantly.'),
  ('Honda', 'Accord', 'RON95', 15.00, 56.00, null, 'estimate', 'Variant/year dependent.'),
  ('Honda', 'WR-V', 'RON95', 17.00, 40.00, null, 'estimate', 'Variant/year dependent.'),
  ('Honda', 'HR-V', 'RON95', 16.70, 40.00, null, 'estimate', 'Petrol/e:HEV hybrid differs significantly.'),
  ('Honda', 'CR-V', 'RON95', 13.90, 57.00, null, 'estimate', 'Variant/year dependent.'),
  ('Honda', 'BR-V', 'RON95', 16.00, 42.00, null, 'estimate', 'Variant/year dependent.'),

  ('Nissan', 'Almera', 'RON95', 18.40, 35.00, null, 'estimate', 'Variant/year dependent.'),
  ('Nissan', 'Serena', 'RON95', 14.20, 60.00, null, 'estimate', 'S-Hybrid variants vary by year.'),
  ('Nissan', 'Navara', 'Diesel', 11.00, 80.00, null, 'estimate', 'Variant/year dependent.'),
  ('Nissan', 'X-Trail', 'RON95', 12.50, 60.00, null, 'estimate', 'Variant/year dependent.'),
  ('Nissan', 'NV200', 'RON95', 12.00, 55.00, null, 'estimate', 'Variant/year dependent.'),
  ('Nissan', 'Urvan', 'Diesel', 9.00, 65.00, null, 'estimate', 'Variant/year dependent.'),

  ('Mitsubishi', 'Triton', 'Diesel', 11.00, 75.00, null, 'estimate', 'Variant/year dependent.'),
  ('Mitsubishi', 'Xpander', 'RON95', 14.50, 45.00, null, 'estimate', 'Variant/year dependent.'),
  ('Mitsubishi', 'Outlander', 'RON95', 12.50, 60.00, null, 'estimate', 'Variant/year dependent.'),
  ('Mitsubishi', 'Pajero Sport', 'Diesel', 10.50, 68.00, null, 'estimate', 'Variant/year dependent.'),

  ('Isuzu', 'D-Max', 'Diesel', 12.00, 76.00, null, 'estimate', 'Variant/year dependent.'),
  ('Isuzu', 'MU-X', 'Diesel', 11.00, 80.00, null, 'estimate', 'Variant/year dependent.'),
  ('Isuzu', 'N-Series', 'Diesel', 7.00, 100.00, null, 'estimate', 'Commercial truck specs vary heavily by body and payload.'),
  ('Isuzu', 'F-Series', 'Diesel', 5.00, 200.00, null, 'estimate', 'Commercial truck specs vary heavily by body and payload.'),

  ('Mazda', 'Mazda 2', 'RON95', 18.90, 44.00, null, 'estimate', 'Variant/year dependent.'),
  ('Mazda', 'Mazda 3', 'RON95', 15.60, 51.00, null, 'estimate', 'Variant/year dependent.'),
  ('Mazda', 'Mazda 6', 'RON95', 14.10, 62.00, null, 'estimate', 'Variant/year dependent.'),
  ('Mazda', 'CX-3', 'RON95', 15.20, 48.00, null, 'estimate', 'Variant/year dependent.'),
  ('Mazda', 'CX-5', 'RON95', 13.50, 56.00, null, 'estimate', 'Petrol/diesel variants differ.'),
  ('Mazda', 'CX-8', 'RON95', 12.50, 72.00, null, 'estimate', 'Petrol/diesel variants differ.'),
  ('Mazda', 'CX-30', 'RON95', 15.60, 51.00, null, 'estimate', 'Variant/year dependent.'),
  ('Mazda', 'BT-50', 'Diesel', 11.00, 76.00, null, 'estimate', 'Variant/year dependent.'),

  ('Hyundai', 'Accent', 'RON95', 14.50, 45.00, null, 'estimate', 'Variant/year dependent.'),
  ('Hyundai', 'Elantra', 'RON95', 14.90, 50.00, null, 'estimate', 'Variant/year dependent.'),
  ('Hyundai', 'Kona', 'RON95', 14.10, 50.00, null, 'estimate', 'Petrol/electric variants differ.'),
  ('Hyundai', 'Tucson', 'RON95', 12.50, 54.00, null, 'estimate', 'Variant/year dependent.'),
  ('Hyundai', 'Santa Fe', 'Diesel', 12.00, 67.00, null, 'estimate', 'Petrol/diesel variants differ.'),
  ('Hyundai', 'Staria', 'Diesel', 10.00, 75.00, null, 'estimate', 'Variant/year dependent.'),
  ('Hyundai', 'H-1', 'Diesel', 9.50, 75.00, null, 'estimate', 'Variant/year dependent.'),

  ('Kia', 'Picanto', 'RON95', 17.00, 35.00, null, 'estimate', 'Variant/year dependent.'),
  ('Kia', 'Cerato', 'RON95', 14.50, 50.00, null, 'estimate', 'Variant/year dependent.'),
  ('Kia', 'Seltos', 'RON95', 15.00, 50.00, null, 'estimate', 'Variant/year dependent.'),
  ('Kia', 'Sportage', 'RON95', 12.50, 54.00, null, 'estimate', 'Variant/year dependent.'),
  ('Kia', 'Sorento', 'Diesel', 12.00, 67.00, null, 'estimate', 'Variant/year dependent.'),
  ('Kia', 'Carnival', 'Diesel', 11.00, 72.00, null, 'estimate', 'Variant/year dependent.'),

  ('Ford', 'Ranger', 'Diesel', 10.50, 80.00, null, 'estimate', 'Variant/year dependent.'),
  ('Ford', 'Everest', 'Diesel', 10.00, 80.00, null, 'estimate', 'Variant/year dependent.'),
  ('Ford', 'Transit', 'Diesel', 9.00, 70.00, null, 'estimate', 'Variant/year dependent.'),

  ('Mercedes-Benz', 'A-Class', 'RON95', 15.00, 43.00, null, 'estimate', 'Variant/year dependent.'),
  ('Mercedes-Benz', 'C-Class', 'RON95', 14.50, 66.00, null, 'estimate', 'Variant/year dependent.'),
  ('Mercedes-Benz', 'E-Class', 'RON95', 13.50, 66.00, null, 'estimate', 'Variant/year dependent.'),
  ('Mercedes-Benz', 'GLA', 'RON95', 14.50, 43.00, null, 'estimate', 'Variant/year dependent.'),
  ('Mercedes-Benz', 'GLC', 'RON95', 12.50, 66.00, null, 'estimate', 'Variant/year dependent.'),
  ('Mercedes-Benz', 'Sprinter', 'Diesel', 9.00, 71.00, null, 'estimate', 'Variant/year dependent.'),
  ('Mercedes-Benz', 'Vito', 'Diesel', 10.00, 70.00, null, 'estimate', 'Variant/year dependent.'),

  ('BMW', '1 Series', 'RON95', 15.00, 42.00, null, 'estimate', 'Variant/year dependent.'),
  ('BMW', '2 Series', 'RON95', 15.00, 42.00, null, 'estimate', 'Variant/year dependent.'),
  ('BMW', '3 Series', 'RON95', 15.20, 59.00, null, 'estimate', 'Petrol/PHEV variants differ.'),
  ('BMW', '5 Series', 'RON95', 14.50, 68.00, null, 'estimate', 'Petrol/PHEV variants differ.'),
  ('BMW', 'X1', 'RON95', 14.50, 54.00, null, 'estimate', 'Variant/year dependent.'),
  ('BMW', 'X3', 'RON95', 13.00, 65.00, null, 'estimate', 'Petrol/PHEV variants differ.'),
  ('BMW', 'X5', 'RON95', 11.00, 83.00, null, 'estimate', 'Petrol/PHEV variants differ.'),

  ('Volkswagen', 'Polo', 'RON95', 15.60, 45.00, null, 'estimate', 'Variant/year dependent.'),
  ('Volkswagen', 'Vento', 'RON95', 16.00, 55.00, null, 'estimate', 'Variant/year dependent.'),
  ('Volkswagen', 'Passat', 'RON95', 14.50, 66.00, null, 'estimate', 'Variant/year dependent.'),
  ('Volkswagen', 'Tiguan', 'RON95', 13.00, 58.00, null, 'estimate', 'Variant/year dependent.'),
  ('Volkswagen', 'Golf', 'RON95', 14.50, 50.00, null, 'estimate', 'Variant/year dependent.'),
  ('Volkswagen', 'Caddy', 'Diesel', 15.00, 55.00, null, 'estimate', 'Variant/year dependent.'),

  ('Subaru', 'XV', 'RON95', 12.80, 63.00, null, 'estimate', 'Variant/year dependent.'),
  ('Subaru', 'Forester', 'RON95', 12.20, 63.00, null, 'estimate', 'Variant/year dependent.'),
  ('Subaru', 'Outback', 'RON95', 11.50, 63.00, null, 'estimate', 'Variant/year dependent.'),
  ('Subaru', 'WRX', 'RON97', 10.50, 63.00, null, 'estimate', 'Variant/year dependent; performance model may require higher RON.'),

  ('Suzuki', 'Swift', 'RON95', 18.00, 37.00, null, 'estimate', 'Variant/year dependent.'),
  ('Suzuki', 'Jimny', 'RON95', 13.50, 40.00, null, 'estimate', 'Variant/year dependent.'),
  ('Suzuki', 'Vitara', 'RON95', 16.00, 47.00, null, 'estimate', 'Variant/year dependent.'),
  ('Suzuki', 'Carry', 'RON95', 12.00, 42.00, null, 'estimate', 'Variant/year dependent.'),

  ('Hino', '300 Series', 'Diesel', 7.00, 100.00, null, 'estimate', 'Commercial truck specs vary heavily by body and payload.'),
  ('Hino', '500 Series', 'Diesel', 5.00, 200.00, null, 'estimate', 'Commercial truck specs vary heavily by body and payload.'),
  ('Hino', '700 Series', 'Diesel', 3.00, 300.00, null, 'estimate', 'Heavy-duty truck; use as placeholder only.'),

  ('Fuso', 'Canter', 'Diesel', 7.00, 100.00, null, 'estimate', 'Commercial truck specs vary heavily by body and payload.'),
  ('Fuso', 'Fighter', 'Diesel', 5.00, 200.00, null, 'estimate', 'Commercial truck specs vary heavily by body and payload.'),

  ('UD Trucks', 'Kuzer', 'Diesel', 7.00, 100.00, null, 'estimate', 'Commercial truck specs vary heavily by body and payload.'),
  ('UD Trucks', 'Croner', 'Diesel', 5.00, 200.00, null, 'estimate', 'Commercial truck specs vary heavily by body and payload.'),
  ('UD Trucks', 'Quester', 'Diesel', 3.00, 300.00, null, 'estimate', 'Heavy-duty truck; use as placeholder only.'),

  ('Volvo', 'XC40', 'RON95', 13.50, 54.00, null, 'estimate', 'Petrol/electric variants differ.'),
  ('Volvo', 'XC60', 'RON95', 12.00, 71.00, null, 'estimate', 'Petrol/PHEV variants differ.'),
  ('Volvo', 'XC90', 'RON95', 10.50, 71.00, null, 'estimate', 'Petrol/PHEV variants differ.'),
  ('Volvo', 'FM', 'Diesel', 3.50, 330.00, null, 'estimate', 'Heavy-duty truck; use as placeholder only.'),
  ('Volvo', 'FH', 'Diesel', 3.00, 400.00, null, 'estimate', 'Heavy-duty truck; use as placeholder only.'),

  ('Tesla', 'Model 3', 'Electric', null, null, 57.50, 'estimate', 'Electric vehicle; use battery capacity instead of fuel tank.'),
  ('Tesla', 'Model Y', 'Electric', null, null, 60.00, 'estimate', 'Electric vehicle; use battery capacity instead of fuel tank.'),
  ('Tesla', 'Model S', 'Electric', null, null, 100.00, 'estimate', 'Electric vehicle; use battery capacity instead of fuel tank.'),
  ('Tesla', 'Model X', 'Electric', null, null, 100.00, 'estimate', 'Electric vehicle; use battery capacity instead of fuel tank.'),

  ('BYD', 'Atto 3', 'Electric', null, null, 60.48, 'estimate', 'Electric vehicle; use battery capacity instead of fuel tank.'),
  ('BYD', 'Dolphin', 'Electric', null, null, 44.90, 'estimate', 'Electric vehicle; standard/extended variants differ.'),
  ('BYD', 'Seal', 'Electric', null, null, 82.50, 'estimate', 'Electric vehicle; standard/extended variants differ.'),
  ('BYD', 'M6', 'Electric', null, null, 71.80, 'estimate', 'Electric vehicle; use battery capacity instead of fuel tank.'),

  ('Chery', 'Omoda 5', 'RON95', 14.90, 51.00, null, 'estimate', 'Petrol/electric variants differ.'),
  ('Chery', 'Tiggo 7 Pro', 'RON95', 13.50, 57.00, null, 'estimate', 'Variant/year dependent.'),
  ('Chery', 'Tiggo 8 Pro', 'RON95', 12.00, 51.00, null, 'estimate', 'Variant/year dependent.'),

  ('GWM', 'Haval H6', 'RON95', 15.00, 61.00, null, 'estimate', 'Hybrid/non-hybrid variants differ.'),
  ('GWM', 'Ora Good Cat', 'Electric', null, null, 47.80, 'estimate', 'Electric vehicle; standard/extended variants differ.'),
  ('GWM', 'Tank 300', 'RON95', 10.00, 80.00, null, 'estimate', 'Variant/year dependent.'),
  ('GWM', 'Cannon', 'Diesel', 10.50, 78.00, null, 'estimate', 'Variant/year dependent.')
on conflict (brand, model) do update set
  default_fuel_type = excluded.default_fuel_type,
  default_fuel_efficiency_km_per_liter =
    excluded.default_fuel_efficiency_km_per_liter,
  default_tank_capacity_liters = excluded.default_tank_capacity_liters,
  default_battery_capacity_kwh = excluded.default_battery_capacity_kwh,
  data_confidence = excluded.data_confidence,
  notes = excluded.notes,
  updated_at = now();
