/// Data model representing an authenticated user.
/// Represents a registered user in the MyFuel application.
///
/// This model stores all information related to a user's account.
/// It will later be used with Firebase Authentication and Firestore.
class UserModel {
  /// Unique user identifier.
  ///Stores the user's unique UUID generated by Supabase Authentication.
  final String id;

  /// User's full name.
  final String fullName;

  /// Username used for logging into the application.
  final String username;

  /// User's email address.
  final String email;

  /// User's phone number.
  final String phoneNumber;

  /// Malaysian IC (NRIC) number.
  final String icNumber;

  /// User's password.
  ///
  /// NOTE:
  /// This is temporary for development.
  ///Passwords are managed by Supabase Authentication
  ///and are never stored in this model.
  final String password;

  /// Indicates whether the user's email has been verified.
  final bool emailVerified;

  /// Date and time when the account was created.
  final DateTime createdAt;

  /// Date and time when the account information was last updated.
  final DateTime updatedAt;

  /// Creates a new UserModel.
  const UserModel({
    this.id = '',
    required this.fullName,
    required this.username,
    required this.email,
    required this.phoneNumber,
    required this.icNumber,
    required this.password,
    this.emailVerified = false,
    required this.createdAt,
    required this.updatedAt,
  });

  factory UserModel.fromJson(Map<String, dynamic> json) {
    return UserModel(
      id: json['id'] ?? '',
      fullName: json['full_name'] ?? '',
      username: json['username'] ?? '',
      email: json['email'] ?? '',
      phoneNumber: json['phone_number'] ?? '',
      icNumber: json['ic_number'] ?? '',
      password: '',
      emailVerified: json['email_verified'] ?? false,
      createdAt: json['created_at'] != null
          ? DateTime.parse(json['created_at'])
          : DateTime.now(),
      updatedAt: json['updated_at'] != null
          ? DateTime.parse(json['updated_at'])
          : DateTime.now(),
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'full_name': fullName,
      'username': username,
      'email': email,
      'phone_number': phoneNumber,
      'ic_number': icNumber,
      'email_verified': emailVerified,
      'created_at': createdAt.toIso8601String(),
      'updated_at': updatedAt.toIso8601String(),
    };
  }
}
